--- 
image: python:latest

stages:
    - Check

Check Linting:
  stage: Check
  before_script:
    - mkdir -p ~/.dotfiles/
    - cp -rv setup/ ~/.dotfiles/setup/
    - mkdir -p ~/.ansible-vault/
    - cp setup/vault.dist.yml ~/.ansible-vault/vault.yml
    - pip3 install ansible
  script:
    - ansible --version
    - cd ~/.dotfiles/setup/
    - ansible-playbook --syntax-check --inventory hosts.yml setup.yml
