---
dist: xenial
language: python
python: "3.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip3 install ansible
script:
  - ansible --version
  - mkdir -p ~/.dotfiles/
  - cp -rv setup/ ~/.dotfiles/setup/
  - mkdir -p ~/.ansible-vault/
  - cp setup/vault.dist.yml ~/.ansible-vault/vault.yml
  - cd ~/.dotfiles/setup/
  - ansible-playbook --syntax-check --inventory hosts.yml setup.yml