---
language: python
python: "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
script:
  - ansible --version
  - mkdir -p ~/.dotfiles/
  - cp -rv setup/ ~/.dotfiles/setup/
  - cd ~/.dotfiles/
  - ansible-playbook --syntax-check --inventory hosts.yml setup.yml