---
userhome: "{{ lookup('env','HOME')|default('~') }}"
vault: '{{ userhome }}/.ansible-vault/vault.yml'
dotfiles: '{{ userhome }}/.dotfiles/'
settings:
  dnscrypt:
    servers: "'cloudflare',  'cloudflare-ipv6'"
    listen: "'127.0.0.1:53', '[::1]:53'" 
    fallback: "'1.1.1.1:53'"
    interfaces: ['Wi-Fi', 'Bluetooth PAN', 'Thunderbolt Bridge', 'Home', 'Mobile']
  shell: '/bin/zsh'
  setup_defaults: True
  extensions:
    vscode: [
        # Common
        md, cfg, ini, conf, ini, 
        sh, zsh, bat, cmd, xml, plist, nfo,
         # LaTEX
        tex
    ]
    quicktime: [
      # Music
      'mp3', 'flac', 'aac', 'wma', 'ogg', 'm4a',
      # Video
      'mpg', 'mkv', 'wmv',
      # Video
      'mp4', 'm4v'
    ]
vm:
  packages:
    chocolatey: [visualstudio2019community]
  settings:
    enable_firewall: True
    setup_script:
      version: 3.8
      presets: [
        # Reference: https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/master/Default.preset
        # Privacy tweaks
        DisableTelemetry, DisableWiFiSense, DisableSmartScreen, DisableWebSearch, DisableAppSuggestions,
        DisableActivityHistory, DisableBackgroundApps, DisableLocation, DisableMapUpdates, DisableFeedback, 
        DisableTailoredExperiences, DisableAdvertisingID, DisableWebLangList, DisableCortana, 
        DisableErrorReporting, SetP2PUpdateDisable, DisableDiagTrack,  DisableWAPPush,
        ## Security tweaks
        DisableSharingMappedDrives, DisableAdminShares, DisableSMB1, DisableSMBServer, DisableLLMNR,
        DisableNCSIProbe, SetCurrentNetworkPrivate, SetUnknownNetworksPublic, DisableNetDevicesAutoInst,
        EnableFirewall, HideDefenderTrayIcon, EnableDefender, EnableDefenderCloud, EnableCtrldFolderAccess,
        EnableCIMemoryIntegrity, EnableDefenderAppGuard, HideAccountProtectionWarn, EnableDownloadBlocking,
        DisableScriptHost, EnableDotNetStrongCrypto, EnableMeltdownCompatFlag, EnableF8BootMenu,
        DisableBootRecovery, DisableRecoveryAndReset, SetDEPOptOut,
        # System tweaks
        DisableUpdateMSRT, DisableUpdateDriver, DisableMaintenanceWakeUp, DisableHomeGroups,
        DisableSharedExperiences, DisableRemoteAssistance, DisableRemoteDesktop, DisableAutoplay,
        DisableAutorun, EnableRestorePoints, EnableStorageSense, DisableDefragmentation, DisableSuperfetch,
        DisableIndexing, EnableSwapFile, EnableNTFSLastAccess, SetBIOSTimeLocal, EnableHibernation,
        DisableSleepButton, DisableSleepTimeout, EnableFastStartup, DisableAutoRebootOnCrash,
        # Application tweaks
        DisableOneDrive, UninstallOneDrive, UninstallMsftBloat, UninstallThirdPartyBloat,
        DisableXboxFeatures, DisableAdobeFlash, DisableEdgePreload, DisableEdgeShortcutCreation,
        DisableIEFirstRun, UninstallMediaPlayer, UninstallInternetExplorer, UninstallWorkFolders,
        UninstallPowerShellV2, SetPhotoViewerAssociation, InstallPDFPrinter, UninstallXPSPrinter, 
        UninstallFaxAndScan, DisableThumbnailCache, DisableThumbsDBOnNetwork,
        UnpinStartMenuTiles, UnpinTaskbarIcons,
      ]
