---
local:
  hosts:
    Dumbledore.local:
      ansible_user: "{{ vault_localhost_username }}"
      ansible_host: localhost
      ansible_connection: local
vm:
  hosts:
    Snape.local:
      ansible_user: "{{ vault_vm_username }}"
      ansible_host: "{{ vault_vm_host }}"
      ansible_password: "{{ vault_vm_password }}"
      ansible_port: 5986
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore