#!/bin/bash
# This returns the vault password from keychain

# Keychain query fields
LABEL="ansible-vault-password"
ACCOUNT_NAME="aaron"

# Command to get vault password from keychain
security find-generic-password -w -a "$ACCOUNT_NAME" -l "$LABEL"