# Beets configuration
library: ~/Music/.library.db
directory: ~/Music/
plugins: edit replaygain fromfilename convert embedart fetchart
ignore_hidden: yes
replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': '' 
  '^\s+': ''
  '^-': _
asciify_paths: yes
ui:
  color: yes
convert:
  auto: yes
  format: mp3
  max_bitrate: 512
  never_convert_lossy_files: yes
  embed: yes
  quiet: false
  command: ffmpeg -i "$source" -y -vn -b:a 320k "$dest"
  extension: mp3
import:
  write: yes
  move: no
  resume: ask
  duplicate_action: ask
paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $albumartist/Singles/$title
  comp: Compilations/$album%aunique{}/$track $title
fetchart:
  cautious: yes
  minwith: 100
  sources: itunes *
embedart:
  remove_art_file: yes
replaygain:
  auto: no
  backend: command
  command: /opt/homebrew/bin/mp3gain
  targetlevel: 89
  noclip: yes
  apply: yes
  overwrite: yes